# Generated by Django 4.1.5 on 2023-02-21 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_author_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='author_category', to='books.category'),
        ),
    ]
